# Regressão Linear
#### É possivel predizer a idade da pessoa a partir dos dados?

In [274]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [275]:
df = pd.read_csv('../datasets/shootings.csv')
df.head()
df.groupby('threat_level').count()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,flee,body_camera,arms_category
threat_level,,,,,,,,,,,,,,
attack,3160,3160,3160,3160,3160,3160,3160,3160,3160,3160,3160,3160,3160,3160
other,1528,1528,1528,1528,1528,1528,1528,1528,1528,1528,1528,1528,1528,1528
undetermined,207,207,207,207,207,207,207,207,207,207,207,207,207,207

In [276]:
data = df.copy()

data['gender'] = (data['gender'] == 'M').astype(int)
data['armed'] = (data['armed'] != 'unarmed').astype(int)
data['flee'] = (data['flee'] != 'Not fleeing').astype(int)
data['signs_of_mental_illness'] = data['signs_of_mental_illness'].astype(int)

data= data.drop(['name','date','id','city','body_camera','manner_of_death','armed','state',
                 'threat_level'], axis=1)
data = pd.get_dummies(data)
data

,age,gender,signs_of_mental_illness,flee,race_Asian,race_Black,race_Hispanic,race_Native,race_Other,race_White,...,arms_category_Explosives,arms_category_Guns,arms_category_Hand tools,arms_category_Multiple,arms_category_Other unusual objects,arms_category_Piercing objects,arms_category_Sharp objects,arms_category_Unarmed,arms_category_Unknown,arms_category_Vehicles
0,53.0,1,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,47.0,1,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,23.0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,32.0,1,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,39.0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890,27.0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4891,23.0,1,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4892,25.0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4893,22.0,1,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4894,31.0,1,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0

In [277]:
X = data.drop('age',axis=1)
y = data['age']
X['intercept'] = 1
c = X.columns.tolist()
c.insert(0,c[-1])
X=X.reindex(columns = c[:-1])
X

,intercept,gender,signs_of_mental_illness,flee,race_Asian,race_Black,race_Hispanic,race_Native,race_Other,race_White,...,arms_category_Explosives,arms_category_Guns,arms_category_Hand tools,arms_category_Multiple,arms_category_Other unusual objects,arms_category_Piercing objects,arms_category_Sharp objects,arms_category_Unarmed,arms_category_Unknown,arms_category_Vehicles
0,1,1,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4891,1,1,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4892,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4893,1,1,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4894,1,1,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0

In [278]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
sc = StandardScaler()

In [279]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2)
Z_train = sc.fit_transform(X_train)
sc.fit(X_train)
Z_test = sc.transform(X_test)
X_train.shape

(3916, 22)

In [280]:
def significants(l):
    return [ int(l.index(i)) for i in l if i>-0.3 and i<0.3 ]

In [281]:
#model = SGDRegressor(max_iter = np.ceil(10**6 / len(Z_train)),tol=1e-5,shuffle=True)
model = Ridge()
model.fit(Z_train,y_train)
y_hat = model.predict(X_test)
err = mean_squared_error(y_test,y_hat)
r2 = r2_score(y_test,y_hat)
print('Erro quadratico:',err,'\nR²:',r2)

Erro quadratico: 151.3960436473858
R²: 0.07475063892654665

In [293]:
idxs = significants(model.coef_.tolist())
new_X = X.drop(X.columns[idxs],axis=1)
y1 = df['age']
new_X['intercept'] = 1
c_val = new_X.columns.tolist()
c_val.insert(0,c[-1])
new_X = new_X.reindex(columns=c_val[:-1])
new_X

,intercept,gender,signs_of_mental_illness,flee,race_Asian,race_Black,race_Hispanic,race_Native,race_Other,race_White,...,arms_category_Explosives,arms_category_Guns,arms_category_Hand tools,arms_category_Multiple,arms_category_Other unusual objects,arms_category_Piercing objects,arms_category_Sharp objects,arms_category_Unarmed,arms_category_Unknown,arms_category_Vehicles
0,1,1,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,1,0,0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
2,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4891,1,1,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4892,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4893,1,1,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
4894,1,1,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0

In [294]:
x1_train,x1_test,y1_train,y1_test = train_test_split(new_X,y1,test_size =0.2)
Z1_train = sc.fit_transform(x1_train)
sc.fit(x1_train)
Z1_test = sc.transform(x1_test)

model.fit(Z1_train,y1_train)
y1_hat = model.predict(x1_test)
err = mean_squared_error(y1_test,y1_hat)
r2 = r2_score(y1_test,y1_hat)
print('Erro quadratico:',err,'\nR²:',r2)

Erro quadratico: 151.33364653418354
R²: 0.07107283289526811