# Regressão Linear
#### É possivel predizer a idade da pessoa a partir dos dados?

In [318]:
import pandas as pd
import numpy as np

In [319]:
df = pd.read_csv('../datasets/shootings.csv')
df.head()
#df.groupby('flee').count()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,arms_category
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,Asian,Shelton,WA,True,attack,Not fleeing,False,Guns
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,White,Aloha,OR,False,attack,Not fleeing,False,Guns
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,Hispanic,Wichita,KS,False,other,Not fleeing,False,Unarmed
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,White,San Francisco,CA,True,attack,Not fleeing,False,Other unusual objects
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,Hispanic,Evans,CO,False,attack,Not fleeing,False,Piercing objects

In [320]:
data = df.copy()
binary_gender = data['gender'] =='M'
binary_gender = binary_gender.astype(int)
data['gender'] = binary_gender

data['armed'] = (data['armed'] != 'unarmed').astype(int)

data['flee'] = (data['flee'] != 'Not fleeing').astype(int)

data['signs_of_mental_illness'] = data['signs_of_mental_illness'].astype(int)
data= data.drop(['name','date','id','city','body_camera'], axis=1)
data = pd.get_dummies(data)
data

,armed,age,gender,signs_of_mental_illness,flee,manner_of_death_shot,manner_of_death_shot and Tasered,race_Asian,race_Black,race_Hispanic,...,arms_category_Explosives,arms_category_Guns,arms_category_Hand tools,arms_category_Multiple,arms_category_Other unusual objects,arms_category_Piercing objects,arms_category_Sharp objects,arms_category_Unarmed,arms_category_Unknown,arms_category_Vehicles
0,1,53.0,1,1,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,47.0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,23.0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,1,32.0,1,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,1,39.0,1,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890,1,27.0,1,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4891,1,23.0,1,0,1,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
4892,0,25.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4893,1,22.0,1,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4894,1,31.0,1,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [321]:
X = data.drop('age',axis=1)
y = data['age']
X['intercept'] = 1
c = X.columns.tolist()
print(c)
c.insert(0,c[-1])
X=X.reindex(columns = c[:-1])
X

['armed', 'gender', 'signs_of_mental_illness', 'flee', 'manner_of_death_shot', 'manner_of_death_shot and Tasered', 'race_Asian', 'race_Black', 'race_Hispanic', 'race_Native', 'race_Other', 'race_White', 'state_AK', 'state_AL', 'state_AR', 'state_AZ', 'state_CA', 'state_CO', 'state_CT', 'state_DC', 'state_DE', 'state_FL', 'state_GA', 'state_HI', 'state_IA', 'state_ID', 'state_IL', 'state_IN', 'state_KS', 'state_KY', 'state_LA', 'state_MA', 'state_MD', 'state_ME', 'state_MI', 'state_MN', 'state_MO', 'state_MS', 'state_MT', 'state_NC', 'state_ND', 'state_NE', 'state_NH', 'state_NJ', 'state_NM', 'state_NV', 'state_NY', 'state_OH', 'state_OK', 'state_OR', 'state_PA', 'state_RI', 'state_SC', 'state_SD', 'state_TN', 'state_TX', 'state_UT', 'state_VA', 'state_VT', 'state_WA', 'state_WI', 'state_WV', 'state_WY', 'threat_level_attack', 'threat_level_other', 'threat_level_undetermined', 'arms_category_Blunt instruments', 'arms_category_Electrical devices', 'arms_category_Explosives', 'arms_category_Guns', 'arms_category_Hand tools', 'arms_category_Multiple', 'arms_category_Other unusual objects', 'arms_category_Piercing objects', 'arms_category_Sharp objects', 'arms_category_Unarmed', 'arms_category_Unknown', 'arms_category_Vehicles', 'intercept']

,intercept,armed,gender,signs_of_mental_illness,flee,manner_of_death_shot,manner_of_death_shot and Tasered,race_Asian,race_Black,race_Hispanic,...,arms_category_Explosives,arms_category_Guns,arms_category_Hand tools,arms_category_Multiple,arms_category_Other unusual objects,arms_category_Piercing objects,arms_category_Sharp objects,arms_category_Unarmed,arms_category_Unknown,arms_category_Vehicles
0,1,1,1,1,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
1,1,1,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,1,0,0
3,1,1,1,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,1,1,1,0,0,1,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4890,1,1,1,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4891,1,1,1,0,1,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
4892,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
4893,1,1,1,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4894,1,1,1,0,1,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [322]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
sc = StandardScaler()

In [324]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2)
Z_train = sc.fit_transform(X_train)
sc.fit(X_train)
Z_test = sc.transform(X_test)
X_train.shape

(3916, 79)

In [406]:
def significants(l):
    return [ int(l.index(i)) for i in l if i>-0.3 and i<0.3 ]

In [407]:
#model = SGDRegressor(max_iter = np.ceil(10**6 / len(Z_train)),tol=1e-5,shuffle=True)
model = Ridge()
model.fit(Z_train,y_train)
y_hat = model.predict(X_test)
err = mean_squared_error(y_test,y_hat)
r2 = r2_score(y_test,y_hat)
print('Erro quadratico:',err,'\nR²:',r2)
coef = model.coef_.tolist()
print(coef.index(min(model.coef_)))
idxs = significants(coef)
idxs

Erro quadratico: 152.53329983646805
R²: 0.07166861472235231
4

[0,
 2,
 5,
 6,
 7,
 15,
 16,
 17,
 18,
 19,
 20,
 23,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 49,
 50,
 51,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 0,
 72,
 75,
 78]

In [408]:
X = X.drop(idxs,axis=1)
X

KeyError: '[0 2 5 6 7 15 16 17 18 19 20 23 26 27 28 29 30 31 32 33 34 35 37 38 39 40\n 41 42 43 44 45 46 49 50 51 53 54 55 56 57 58 59 61 62 63 64 65 66 67 68\n 69 0 72 75 78] not found in axis'